spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: Long6617
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.207.133
    port: 5672
    username: guest
    password: guest
env:
  product12
