spring: 
  redis:
    host: 192.168.207.133
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=utf-8&useSSL=false
    username: root
    password: Long6617
